name: tutorial_check

on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  group: ${{
    ( github.ref == 'refs/heads/master' &&
    format('{0}/{1}', github.run_id, github.run_attempt) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

env:
  ZKLLVM_VERSION: 0.0.58
  TOOLCHAIN_VERSION: 0.0.31

jobs:
  test-zkllvm-workflow:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Pull the zkLLVM image
        run: scripts/run.sh --verbose pull_zkllvm

      - name: Compile a circuit
        run: scripts/run.sh --verbose --docker compile

      - name: Make constraint and assignment table (optional)
        run: scripts/run.sh --verbose --docker run_assigner

      - name: Pull the toolchain image
        run: scripts/run.sh --verbose pull_pm_toolchain

      - name: Build a statement for the Proof Market
        run: scripts/run.sh --verbose --docker build_statement

      - name: Calculate a proof
        run: scripts/run.sh --verbose --docker prove
